### ISSUE TITLE
Making Tests Creates a -p Directory

### ISSUE THREAD

**Issue by acuba001** [Superstar64/aith#1]
After building aith successfully, I try to run `make tests` and the following error occurs:
<img width="436" alt="image" src="https://user-images.githubusercontent.com/4492431/202859025-b456d124-86b8-4b02-b566-77c7c4637a01.png">

I also noticed that a `-p` directory was created in the project directory
<img width="226" alt="image" src="https://user-images.githubusercontent.com/4492431/202859491-543dab76-a4cb-4f40-9b31-fa5637b54bf3.png">

I am not too familiar with the code, but I believe the following line is the culprit:
https://github.com/Superstar64/aith/blob/d48d5696f0df54140d8ba09c5193cc2df3ef4b65/GNUmakefile#L16
I think when running `make tests` at some point `mkdir dist-newstyle/aith -p` is ran where maybe it should be `mkdir -p dist-newstyle/aith`. According to `man mkdir` the `-p` flag must come immediately after `mkdir`.

If this is not the case, an explanation would be welcomed and greatly appreciated.

**Comment by Superstar64** [comment]
Hmm, GNU mkdir takes `-p` after the directory, so this is probably a GNU extension. Let me fix this.
